### ISSUE TITLE
dtend/dtsart times off by TZ offsett

### ISSUE THREAD

**Issue by jedgell** [bryckbost/michromeformats#1]
That is to say, I'm building a site and using your _wonderful!!!_ plugin to debug my microformats on calendar and location items and I'm seeing that the dtstart/dtend dates are off on every entry by the timezone offsett. I tried looking through the code (and I'm sorry to say I can't dedicate more time to it at the moment), but couldn't find anything glaring. My assumption is that you're assuming a UTC timestamp and subtracting the offset, making a timestamp of 2010-07-11T15:00:00-0400 appear to start at 11AM locally, when it should be (properly) converted to 7PM UTC, if there is no 'tz' element set. And...I just saw how to fix my self created glitch. I set the tz element in the html and it works, but your scripts shouldn't rely on it, as it isn't required (especially if you're adding the offset).

Anyway, thank-you for this wonderful tool!

**Comment by bryckbost** [comment]
Thanks!

I'll take a look at the timezone offset and see if I can get it straightened out.
