### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by burntime** [bryckbost/michromeformats#10]
HTML entity escaped JavaScript will be executed in the popup view.

Example: 

```
&lt;script&gt;
document.body.style.backgroundColor = &quot;lime&quot;
&lt;/script&gt;
```

Demo: http://brbforum.de/mfxss.html

**Comment by bryckbost** [comment]
Fixed in [9a2b74](https://github.com/bryckbost/michromeformats/commit/9a2b74b2ea0d608295454bf03f40d87b6d1e6a12)
