### ISSUE TITLE
value-title

### ISSUE THREAD

**Issue by burningice2866** [bryckbost/michromeformats#2]
The parser needs to be able to recognize the value-title pattern for machine added data.

http://microformats.org/wiki/value-class-pattern#Using_value-title_to_publish_machine-data

**Comment by awaer** [comment]
It also seems to fail on split values, e.g. http://microformats.org/wiki/value-dt-test-YYYY-MM-DD--H-MMam-Epm 

It gets the date correct, but fails on the start time and implied end date/time.

**Comment by bryckbost** [comment]
Fixed in most recent release.
