### ISSUE TITLE
hreview-aggregate support

### ISSUE THREAD

**Issue by ThomasArdalTrifork** [bryckbost/michromeformats#6]
It would be nice to support hreview-aggregate: http://microformats.org/wiki/hreview-aggregate

**Comment by bryckbost** [comment]
Hadn't come across this before. Looks good, I'll check it out.

Patches are always welcome by the way.

**Comment by ThomasArdal** [comment]
I will implement hreview-aggregate Wednesday next week.

**Comment by ThomasArdal** [comment]
I've implemented this and waiting for two things:
- new icon from a designer I know
- help from a college to get my changes back into git

**Comment by bryckbost** [comment]
Awesome. Feel free to push what you have and we can add the icon whenever you get it from the designer.

**Comment by ThomasArdal** [comment]
The feature is implemented in the following three commits:

https://github.com/ThomasArdal/michromeformats/commit/c3adfcbc689b0461f9fbac92c5cf52d11a96016c
https://github.com/ThomasArdal/michromeformats/commit/24847334b1afb4a014d1598db06348dba699eac5
https://github.com/ThomasArdal/michromeformats/commit/140ec9c10bcb4b7949241336e0c1560e95c90b40

Sorry for pushing three times, but I'm kind of a Git Noob :)
