### ISSUE TITLE
hrecipe not being recognized

### ISSUE THREAD

**Issue by toneplex** [bryckbost/michromeformats#8]
Google's rich snippet tool shows the hrecipe data: http://www.google.com/webmasters/tools/richsnippets?url=http%3A%2F%2Fwww.justapinch.com%2Frecipe%2Flovelucy%2Fmango-cobbler%2Ffruit-dessert&view=
but when going to http://www.justapinch.com/recipe/lovelucy/mango-cobbler/fruit-dessert  this extension doesn't show the hrecipe data.

This might be related to issue #5.

**Comment by agarcia-oss** [comment]
This seems to be working fine with the last version of the extension....

**Comment by toneplex** [comment]
Yes it is working now. Thanks for the fix.
